name: Update docker image

on:
  workflow_dispatch:      # Trigger by hand from the UI
  release:
    types: released
  push:
    branches:
      - develop

jobs:
  build-and-release-docker-image:
    name: Builds a dockerimage with the python bindings of preCICE
    runs-on: ubuntu-latest
    env:
        docker_username: precice
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v2
        with:
          push: true
          file: "./tools/releasing/packaging/docker/Dockerfile"
          tags: ${{ env.docker_username }}/python-bindings:${GITHUB_REF##*/},${{ env.docker_username }}/python-bindings:latest
          build-args: |
            branch=${GITHUB_REF##*/}
