name: Build Spack
on:
  push:
    branches:
      - "*"
      
jobs:  
  build_spack:
    name: build_spack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: precice/ci-spack-pyprecice-deps-1804
    defaults:
      run:
        shell: "bash --login -eo pipefail {0}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Move Package Script
        run: |
          cp spack/repo/packages/py-pyprecice/package.py /sources/spack/repo/packages/py-pyprecice/
          cp spack/repo/packages/py-pyprecice/*.patch /sources/spack/repo/packages/py-pyprecice/
      - name: Try to build py-pyprecice with spack
        run: |
          . /opt/spack/share/spack/setup-env.sh && spack env activate ci && spack dev-build py-pyprecice@develop
      - name: Import precice and print version
        run: |
          . /opt/spack/share/spack/setup-env.sh && spack env activate ci && python3 -c "import precice; print(precice.__version__)"
