name: Update build environment

on:
  workflow_dispatch:      # Trigger by hand from the UI
  schedule:
    - cron: '0 0 * * 0'   # Schedule it every Sunday
  push:                   # Trigger on push, since dispatch does not work if not on default branch. See https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install pip3
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
      - name: Install jinja2
        run: pip3 install --user jinja2
      - name: Specify Package Script
        run: |
          python3 spack/jinja-instantiate.py --branch develop > spack//opt/spack/var/spack/repos/builtin/packages/py-pyprecice/package.py
          ls spack/var/spack/repos/builtin/packages/py-pyprecice
          cp spack/var/spack/repos/builtin/packages/py-pyprecice/*.patch /opt/spack/var/spack/repos/builtin/packages/py-pyprecice/
          ls spack/var/spack/repos/builtin/packages/py-pyprecice
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: spack/ci-spack-pyprecice-deps-1804.dockerfile
          tags: precice/ci-spack-pyprecice-deps-1804
